# Generated by Django 4.1.3 on 2022-11-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
    ]
