# Generated by Django 4.1.3 on 2022-11-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ID',
        ),
    ]
